services:
  db:
    image: postgres:16
    container_name: jp_digest_db
    environment:
      POSTGRES_USER: jp
      POSTGRES_PASSWORD: jp
      POSTGRES_DB: jp_digest
    ports:
      - "5432:5432"
    volumes:
      - jp_digest_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jp -d jp_digest" ]
      interval: 5s
      timeout: 3s
      retries: 20
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: jp_digest_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jgehunter@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  jp_digest_pgdata:
